### ISSUE TITLE
totally not work in vscode

### ISSUE THREAD

**Issue by zzzgit** [dai-shi/es-beautifier#11]
I installed this plugin for vscode,and it din't work at all.
What is wrong?
should I config something here first?

![image](https://cloud.githubusercontent.com/assets/1060733/22919413/b6baac6e-f2ca-11e6-8a45-1bf1034801b8.png)

**Comment by dai-shi** [comment]
Hi,

There's a short description here: https://github.com/dai-shi/es-beautifier#usage-visual-studio-code

Can you try Cmd-K M or Ctrl-K M to open the Change Language Mode and select "es-beautifier".
You can then press Shift-Option-F or Shift-Alt-F or Ctrl-Shift-I to run it.

ref: http://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode

Hope it helps!

**Comment by zzzgit** [comment]
@dai-shi
it still doesn't work
and what i want say is that `Shift-Alt-F` is for the built-in formater command,not for `es-beautifier`

**Comment by dai-shi** [comment]
Yes, it essentially changes the built-in formatter command. You can refer the history why and how it's changed in #6.

How about opening the Change Language Mode and select "es-beautifier"? not successful?

**Comment by zzzgit** [comment]
I tried what you have said but it doesn't work
thanks
and i found [this plugin](https://github.com/Microsoft/vscode-eslint) could do what i want
i will use this one instead

**Comment by dai-shi** [comment]
It's good that you found a solution.

That reminds me of some notes:
- es-beautifier uses eslint internally with some additional formatting rules, but it's not the eslint plugin.
- es-beautifier have its own configuration and it ignores user `.eslitrc` files by default. This is being fixed in #9.
- as it uses eslint internally, es-beautifier fails formatting if there's a syntax error, and simply does nothing in that case.

**Comment by dai-shi** [comment]
Let me close this issue. Please feel free to open a new issue if you still have a problem.
