### ISSUE TITLE
Ignores indent rules

### ISSUE THREAD

**Issue by langdonx** [dai-shi/es-beautifier#9]
`es-beautifier` appears to always apply 2 spaces for indention, regardless of what is configured (4 spaces, 1 tab, etc).  To ensure I had the configuration right, I ran `eslint --fix` manually, which does adhere to the configured value.

I'm running VS Code (was 1.8, 1.9 as of this morning).

TIA!

**Comment by dai-shi** [comment]
Yes, es-beautifier doesn't use eslint configs, and it has its own rules specified in [config/standard.js](https://github.com/dai-shi/es-beautifier/blob/master/lib/configs/standard.js).


You could customize it if you use es-beautifier as an [eslint plugin](https://www.npmjs.com/package/eslint-plugin-es-beautifier), but since you are using VS Code, it's not an option.

Our option is to provide another config file and provide options to specify it in the vscode plugin configuration. How does that sound?

**Comment by langdonx** [comment]
Ahh, interesting. I made the assumption that this would use `.eslintrc` to format Javascript. Sort of an enhanced `eslint --fix`.  Pointing to a separate config would be fine.

**Comment by dai-shi** [comment]
Hm, it might be possible to read user eslintrc files. I've never tried, but we could try. The only concern is if there's conflicting rules, and users should take care of it.

**Comment by dai-shi** [comment]
@langdonx vscode extension v0.2.2 is published. please give it a try.
You can now configure like the following:
```
    "[es-beautifier]": {
        "useEslintrc": true
    }
```
in your settings. (which warns `Unknown Identifier. Use language identifiers`, not sure how to fix this.)
Please note that I haven't really tested with a local .eslintrc file.

**Comment by langdonx** [comment]
Cool! Thank you! Which config/settings file in my VS Code work space does that new setting belong in?

**Comment by dai-shi** [comment]
It reads from the workspace settings, but I tested with user settings, so both should work.

Please let me know if I misunderstood your question.

**Comment by dai-shi** [comment]
<img width="444" alt="image" src="https://cloud.githubusercontent.com/assets/490574/22619713/35c5e206-eb3e-11e6-91f2-a050fb9cb9a1.png">

Just to share my settings...

**Comment by dai-shi** [comment]
Let me close this issue. Hopefully it's fixed, please feel free to reopen for further discussions.
